baseURL = 'https://localhost'
title = 'Rework-Space local'
timeout = 300000
theme = ["rs-theme"]
#theme = ["gitlab.com/rework-space.com/rs-site/rs-theme"]

DefaultContentLanguage = "en"
Paginate = 3 # for blog page
enableRobotsTXT = true

[taxonomies]
  tag = "tags"
  category = "categories"
  blog = "blogs"

[languages]
  [languages.en]
    languageCode = 'en'
    title = "Rework-Space"
    weight = 1
    contentDir = "content/en"
    [languages.en.menus]
    [[languages.en.menus.main]]
      name = 'Careers'
      url = 'https://opportunity.rework-space.com/jobs/Careers-at-Rework-Space'
      weight = 5
    [languages.en.params]
      footerContactButton = "Contact us"
      footerContactButtonPath = '/about/contacts/'
      footerPrivacy = 'Privacy'
      footerPrivacyUrl = '/about/privacy'
      customFooterLine1 = "10 Berezhans'ka St, office 82"
      customFooterLine2 = '46027, Ternopil, Ukraine'
      customFooterLine3 = '+38 067 324 6141'
      read_more_button = 'Read more ->'
      tags = 'Tags'
      blog = 'Blog'
      all_articles = 'All articles'
      date_prefix = 'Published #'
      consent_manage = 'Manage preferences'
      consent_deny = 'Deny'
      consent_allow = 'Allow'
      consent_outer_message_1 = 'We would like to use '
      consent_outer_message_2 = ' to improve the functionality of this website.'
      consent_inner_message = 'third party code'
      consent_description = 'This code gives us insight into the number of people that visit our website, where they are from and what they are clicking on.'
      consent_details_link_name = 'Privacy statement'
      consent_details_link = '/about/privacy/#cookies'
      consent_details = 'Details'
      consent_allow_all = 'Allow all'
      consent_save_preferences = 'Save preferences'
  [languages.ua]
    languageCode = 'ua'
    title = "Rework-Space"
    weight = 2
    contentDir = "content/ua"
    [languages.ua.menus]
    [[languages.ua.menus.main]]
      name = "Кар'єра"
      url = 'https://opportunity.rework-space.com/jobs/Careers-at-Rework-Space'
      weight = 6
    [languages.ua.params]
      footerContactButton = "Зв'яжіться з нами"
      footerContactButtonPath = '/ua/about/contacts/'
      footerPrivacy = 'Конфіденційність'
      footerPrivacyUrl = '/about/privacy'
      customFooterLine1 = 'вул. Бережанська 10, офіс 82'
      customFooterLine2 = 'м.Тернопіль, 46027,  Україна'
      customFooterLine3 = '+38 068 699 3913'
      read_more_button = 'Детальніше ->'
      tags = 'Теги'
      blog = 'Блог'
      all_articles = 'Усі статті'
      date_prefix = 'Опубліковано #'
      consent_manage = 'Керувати налаштуваннями'
      consent_deny = 'Відмовити'
      consent_allow = 'Дозволити'
      consent_outer_message_1 = 'Ми хотіли б використовувати '
      consent_outer_message_2 = ' для покращення функціональності даного вебсайту.'
      consent_inner_message = 'сторонній код'
      consent_description = 'Цей код дає нам уявлення про кількість людей, які відвідують наш веб-сайт, звідки вони та що вони натискають.'
      consent_details_link_name = 'Політика конфіденційності'
      consent_details_link = '/ua/about/privacy/#cookies'
      consent_details = 'Детальніше'
      consent_allow_all = 'Дозволити всі'
      consent_save_preferences = 'Зберегти обрані'

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  google_tag_manager = 'GTM-devel'
  text_color = ""
  middle_title_color_code = "#008080"
  link_color = "#008080"
  author = ""
  favicon = '/general-images/rework_logo.webp'
  siteLogo = '/general-images/rework_logo_10grey_008080.webp'
  siteLogoMobile = '/general-images/rework_logo.webp'
  mobileMenuLight = true
  header_image_line = '/general-images/background_photo_line.webp'
  header_background_image = '/general-images/background_photo.webp'
  default_sharing_image = '/general-images/rework_logo_white_bg.png'
  description = "Modern solutions that become the basis for innovation and help businesses achieve bold goals. At Rework-Space, we take a holistic approach to providing professional services."
  background_color_class = "bg-mid-gray" # header and footer default background color. Choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  body_classes = "avenir bg-white" # font and body background color
  recent_posts_number = 3 # for index page
  date_format = '2006-01-02'
  post_content_classes = "avenir"
  gtm = "GTM-dev"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/rework_space"
label = "Twitter"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/company/rework-space/"
label = "Linkedin"

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/com.rework.space/"
label = "Facebook"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/rework-space-com"
label = "GitHub"

[[params.ananke_socials]]
name = "gitlab"
url = "https://gitlab.com/rework-space.com/"
label = "GitLab"